// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8wA5_C3vdX6vwq0pUMgmIzU-H_MyG1Xo',
    appId: '1:595875344046:web:81337a0f6c87bfee73c73f',
    messagingSenderId: '595875344046',
    projectId: 'blocfirebasesir',
    authDomain: 'blocfirebasesir.firebaseapp.com',
    databaseURL: 'https://blocfirebasesir-default-rtdb.firebaseio.com',
    storageBucket: 'blocfirebasesir.firebasestorage.app',
    measurementId: 'G-L72FKB6NF2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDeKRAaJX2JZHMX7WoRcfApz4kBYruAfXo',
    appId: '1:595875344046:android:b12db229eb69412173c73f',
    messagingSenderId: '595875344046',
    projectId: 'blocfirebasesir',
    databaseURL: 'https://blocfirebasesir-default-rtdb.firebaseio.com',
    storageBucket: 'blocfirebasesir.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAixDtwbdtcE1kkDDoLhskXrzByVpYi7qo',
    appId: '1:595875344046:ios:1faf55a69895cf1173c73f',
    messagingSenderId: '595875344046',
    projectId: 'blocfirebasesir',
    databaseURL: 'https://blocfirebasesir-default-rtdb.firebaseio.com',
    storageBucket: 'blocfirebasesir.firebasestorage.app',
    iosBundleId: 'com.example.apiCalling',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAixDtwbdtcE1kkDDoLhskXrzByVpYi7qo',
    appId: '1:595875344046:ios:1faf55a69895cf1173c73f',
    messagingSenderId: '595875344046',
    projectId: 'blocfirebasesir',
    databaseURL: 'https://blocfirebasesir-default-rtdb.firebaseio.com',
    storageBucket: 'blocfirebasesir.firebasestorage.app',
    iosBundleId: 'com.example.apiCalling',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA8wA5_C3vdX6vwq0pUMgmIzU-H_MyG1Xo',
    appId: '1:595875344046:web:7c326e8575ce9ff273c73f',
    messagingSenderId: '595875344046',
    projectId: 'blocfirebasesir',
    authDomain: 'blocfirebasesir.firebaseapp.com',
    databaseURL: 'https://blocfirebasesir-default-rtdb.firebaseio.com',
    storageBucket: 'blocfirebasesir.firebasestorage.app',
    measurementId: 'G-2044055P0G',
  );
}
